### PR TITLE
feat: add call-chaining search support for advanced filtering and querying operations

### LINKED ISSUE #130: Boolean filters support
https://github.com/benhutchins/dyngoose/blob/master/src/query/filters.ts#L7

I see this line commented just wanted to check if this is in the roadmap? or is it simply a matter uncommenting and adding AND and NOT?

### PR DESCRIPTION
**Pull request by benhutchins**
Fixes #130

#### Is it a breaking change?: YES

This now breaks the `Table.search` method, which will no longer return the results directly, but instead returns the `MagicSearch` class which then needs to be called with `.exec()`. Additionally, I've deprecated the `MagicSearch.search()` method in favor of naming it `MagicSearch.exec()`.

### Why did you make these changes?

1. Adding support for `OR` conditions, an import feature to support for basic querying.
2. Adding support for complex query building using call-chaining, but with strict typing enforcement.

### What's changed in these changes?

All `Filters` can now be an array. You can then pass filter objects like normal, or an additional array acts as a set of OR conditions. Example:

```typescript

MyTable.gsiIndex.search()
  .filter('account').eq('some account id')
  .parenthesis((s) =>
    s.parenthesis((ss) =>
      ss.filter('status').eq('pending')
         .and()
         .filter('owner').eq('user id')
     )
     .or()
     .filter('status', 'active')
   )

// this makes a query that looks like:
// account = 'some account id' AND ((status = 'pending' AND owner = 'user id') OR status = 'active')
})
```

### What do you especially want to get reviewed?

NSTR.

### Is there any other comments that every teammate should know?

NSTR.

### Submission Type

* [ ] Bugfix
* [X] New Feature
* [ ] Refactor

### All Submissions

* [X] Have you added an explanation of what your changes?
* [X] Have you written new tests for your changes, as applicable?
* [X] Have you checked potential side effects that could make bad impacts to other services?

### New Features

* [X] Have you configured CI/CD properly?
* [X] Have you configured optimal memory size and timeouts of Lambda Function?
* [X] Have you grant required permissions (e.g. IAM Policy, VPC Security Group)?
* [X] Have you made required resources (e.g. DynamoDB Table, RDS Cluster)?
* [ ] Does it requires native addons dependency?

### CODE REVIEW

**Comment by visheshd** [comment]
Explicit syntax would be more readable: 

```

 MyTable.gsiIndex.query([
  { account: 'some account id' },
  'OR': [
    { status: 'pending', owner: 'user id' },
    { status: 'active' }
  ]
})

```

Also might be better to make `parse` in expression.ts recursive to allow nested conditions and might improve DRYness of `parse`

**Comment by MuazOthman** [comment]
Hi guys,

Great work! Any expected date for this to be released?

**Comment by benhutchins** [comment]
I've updated the implementation for this, based on a suggestion from @visheshd; adding support for call-chaining query building (similar to the style used by Mongoose and Dynmoose), but in a way that keeps strict TypeScript typing enforcement.

I need to expand the unit tests more before I merge, and this will result in an API change to the `Table.search` method.

**Comment by benhutchins** [comment]
I've completed the implementation and documentation for the updates. Now just need to expand the unit tests to be a bit more confident everything operates correctly.

If either of you have time to test it out and/or provide feedback, I'd love to get some input before proceeding with this update.

I'm going to tag in @franbueno as well to get some feedback from him.

**Comment by visheshd** [comment]
Sorry about the late response. This looks great. I had one comment

```typescript 

MyTable.gsiIndex.search()
  .filter('account').eq('some account id')
  .and()  // <<<<<<<<<<<<<<<<<<< is this missing above or by design? Might make things more explicit.
  .parenthesis((s) =>
    s.parenthesis((ss) =>
      ss.filter('status').eq('pending')
         .and()
         .filter('owner').eq('user id')
     )
     .or()
     .filter('status', 'active')
   )
```

On a side not I was exploring single table design for something and wondering if you've used Dyngoose for the same. Looks like it might be doable but wanted to check with you before diving deeper. @benhutchins

**Comment by benhutchins** [comment]
`.and()` exists, it's just optional, by default it joins segments with and; unless you use `.or()`.

As for single table design, yes, Dyngoose should support it. You just need to setup your partition keys correctly. There are pros and cons to the setup, it really depends on the app, type of data, and its usage whether a single table design would make sense to use, but I have utilized the concept several times to make "joining" unnecessary.

I have considered creating a "Dyngoose.Attribute.Reference" attribute type which would reference another table class and then handle storing most of the data from the referenced record within a Dynamodb Map attribute, allowing you to easily handle querying without joins, and it would the auto-create the record instance for you.

```typescript
class Order {
  @Dyngoose.Attribute.Ref(User)
  user: User
}

const user = User.new()
const order = Order.new({ user })

await user.save()
await order.save()

const orders = await Order.primaryKey.scan()

orders.results[0].user // would be defined and contain data without having to query for user
```

**Comment by visheshd** [comment]
Ref would be interesting ... We are current embedding objectes manually using Maps. 

But this use case seems like would be difficult to implement with Dyngoose 
73772626-1e4f0780-4746-11ea-84f4-1490119d7cd6

[Details here ](https://www.alexdebrie.com/posts/dynamodb-single-table/)

**Comment by benhutchins** [comment]
I've been giving this some thought and I believe it would take some refactoring to really support Single Table Design well with Dyngoose. I understand the benefits of it and I believe there is some work from dynamodb-toolbox that might be able to benefit that work, but it would get fairly complicated.

A simple approach to using Single Table Design with Dyngoose would be to simply use a table and handle the partition and sort keys:

```typescript
export class SingleTableExample extends Dyngoose.Table {
  @Dyngoose.$PrimaryKey('pk', 'sk')
  public static readonly primaryKey: Dyngoose.Query.PrimaryKey<SingleTableExample, number, string>

  @Dyngoose.Attribute.String()
  pk: string

  @Dyngoose.Attribute.String()
  sk: string

  @Dyngoose.Attribute.String()
  fullName: string

  @Dyngoose.Attribute.String()
  email: string

  @Dyngoose.Attribute.String()
  address: string

  @Dyngoose.Attribute.String()
  status: string

  @Dyngoose.Attribute.String()
  orderId: string

  @Dyngoose.Attribute.Date({
    nowOnCreate: true,
  })
  createdAt: Date
}

export async function createUserProfile(data: {
  username: string
  fullName: string
  email: string
  address: string
}): Promise<SingleTableExample> {
  const profile = SingleTableExample.new({
    pk: `USER#${data.username}`,
    sk: `#PROFILE#${data.username}`,
    fullName: data.fullName,
    email: data.email,
    address: data.address,
  })

  await profile.save()
  return profile
}

export async function createOrder(data: {
  username: string
  fullName: string
  address: string
  status: string
  orderId: string
}): Promise<SingleTableExample> {
  const order = SingleTableExample.new({
    pk: `USER#${data.username}`,
    sk: `ORDER#${data.orderId}`, // I feel like this should be the order datetime, not the order id
    fullName: data.fullName,
    orderId: data.orderId,
    address: data.address,
    status: data.status,
  })

  await order.save()
  return order
}

export async function getUserAndOrders(username: string): Promise<{ profile: SingleTableExample, orders: SingleTableExample[] }> {
  const query = await SingleTableExample.primaryKey.query({ pk: `USER#${username}` })
  const profile = query.records.find((r) => r.sk.startsWith('#PROFILE'))

  if (profile == null) {
    throw new Error('No profile for user')
  }

  return {
    profile,
    orders: query.records.filter((r) => r.sk.startsWith('ORDER')),
  }
}
```

This is a fairly simple example, where some attributes are not being set depending on the entity being created within the table. When you query, you query by the username to get all the orders. There would need to be a bit more work to handle the possibility of paging.

**Pull request merged**
